plugins {
    alias(libs.plugins.android.application)
    id 'com.google.gms.google-services'
}

android {
    namespace 'com.example.mugangaconnect'
    compileSdk 35

    defaultConfig {
        applicationId "com.example.mugangaconnect"
        minSdk 24
        targetSdk 35
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        Properties properties = new Properties()
        if (project.rootProject.file('local.properties').exists()) {
            properties.load(project.rootProject.file('local.properties').newDataInputStream())
        }

        def geminiApiKey = properties.getProperty("GEMINI_API_KEY") ?: project.findProperty("GEMINI_API_KEY") ?: System.getenv("GEMINI_API_KEY") ?: ""
        if (geminiApiKey.isEmpty()) {
            logger.warn("GEMINI_API_KEY is missing. Generative AI features will not work.")
        }
        buildConfigField "String", "GEMINI_API_KEY", "\"${geminiApiKey}\""
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    buildFeatures {
        buildConfig true
        viewBinding true
    }
    dependenciesInfo {
        includeInApk true
        includeInBundle true
    }
}

dependencies {
    implementation libs.appcompat
    implementation libs.material
    implementation libs.activity
    implementation libs.constraintlayout
    implementation libs.cardview
    implementation libs.recyclerview
    implementation libs.blurview
    implementation libs.lucide.icons
    implementation libs.biometric

    // Firebase BoM — manages all Firebase library versions
    implementation platform(libs.firebase.bom)
    implementation libs.google.firebase.auth
    implementation libs.google.firebase.firestore
    implementation libs.google.firebase.messaging
    implementation libs.generativeai
    implementation libs.security.crypto
    
    // Cloudinary for image upload
    implementation libs.cloudinary.android
    implementation libs.cloudinary.core
    
    // Glide for image loading
    implementation libs.glide
    annotationProcessor libs.compiler

    // Room
    implementation libs.room.runtime
    annotationProcessor libs.room.compiler
    
    testImplementation libs.junit
    androidTestImplementation libs.ext.junit
    androidTestImplementation libs.espresso.core
}
